//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aidify.Admin
{
    public partial class AI_Insights
    {
        protected global::System.Web.UI.WebControls.Literal litAIStatus;
        protected global::System.Web.UI.WebControls.TextBox txtAdminQuestion;
        protected global::System.Web.UI.WebControls.Button btnAskAI;
        protected global::System.Web.UI.WebControls.Literal litAIResponse;
    }
}
